In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors
Creating Tensors

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [ ]:
deneme = torch.tensor([ [[[1, 0], [1, 0
                                   ]]]])

In [ ]:
deneme.ndim

4

In [ ]:
deneme.shape

torch.Size([1, 1, 2, 2])

In [ ]:
# random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3648, 0.8710, 0.5306, 0.1314],
        [0.2681, 0.9270, 0.6130, 0.3124],
        [0.1455, 0.8117, 0.0030, 0.9904]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# tensors with 0s and 1s
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
#create range of tensors and tensorslike
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [ ]:
one_to_ten = torch.arange(1, 11, 1)
# for same shape use "like"
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
# tensor not right data type
# tensor not right shape
# tensor not on right device

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9156, 0.5877, 0.3268, 0.4437],
        [0.8289, 0.7742, 0.7924, 0.1867],
        [0.1921, 0.0074, 0.8327, 0.9421]])

In [ ]:
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Tensor Ops

In [ ]:
#create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
# subtraction
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# in built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# 2 ways : -element wise -matrix mul



In [ ]:
# element wise
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# matrix multiplications = dot product
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

CPU times: user 1.75 ms, sys: 0 ns, total: 1.75 ms
Wall time: 1.49 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 606 µs, sys: 0 ns, total: 606 µs
Wall time: 483 µs


tensor(14)

In [ ]:
# @  stands for matrix multiplication

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B ) # torch.matmul = torch.mm
# shapes do not match
# manipulate shape using transpose
# transpose switches axes

RuntimeError: ignored

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T )

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

## Tensor Aggregation

In [ ]:
# min, max, sum... etc

x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
# mean function requires a tensor of float32 dtype
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
# finding position of min and max
# returns index of min value
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
# reshaping: tensor => defined shape
# view: same as reshaping but keep the same mem
# stacking: combine multiple tensors on top of each other or side by side
# squeezing: removes all 1 dimensions from a tensor
# unsqueezing: add 1 dimension to a target tensor
# permute: permute / swap in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dim
x_reshaped = x.reshape(3, 3) # must meet up to total # of elements
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z (view) changes x, they have the same ref

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# squeeze
x_reshaped_2 = x.reshape([1, 9])
x_reshaped_2.shape

torch.Size([1, 9])

In [ ]:
x_reshaped_2.squeeze().shape
# removes all 1 dims

torch.Size([9])

In [ ]:
x_reshaped_2.squeeze().unsqueeze(0).shape

torch.Size([1, 9])

In [ ]:
# permute rearranges the dims in specified order
x_original = torch.rand(size=(224, 224, 3))

#permute to dim order
# ilk index e hangi indexin gelmesini istediğini yaz
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

## indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][1]

tensor([4, 5, 6])

In [ ]:
x[0][2][1]

tensor(8)

In [ ]:
# select all with :
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
 #pytorch tensors and numpy


# numpy to pytorch
# numpy default is float64

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
 #pytorch tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# reproducibility

#set the random seed
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B

(tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]]),
 tensor([[0.0290, 0.4019, 0.2598, 0.3666],
         [0.0583, 0.7006, 0.0518, 0.4681],
         [0.6738, 0.3315, 0.7837, 0.5631]]))

## GPU OPS

In [ ]:
# running tensors and pytorch objects on the gpus
!nvidia-smi

import torch
torch.cuda.is_available()


Sat Nov 18 17:45:25 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count # of devices
torch.cuda.device_count()

1

In [ ]:
# putting tensors and models on the gpu

tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# moving tensors back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])